-- Create projects table
create table public.projects (
  id uuid not null,
  title text not null,
  description text null,
  status text not null,
  priority text null,
  budget numeric(15, 2) null default 0,
  spent numeric(15, 2) null default 0,
  start_date date not null,
  end_date date not null,
  actual_end_date date null,
  created_by uuid null,
  archived_at timestamp without time zone null,
  created_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  updated_at timestamp without time zone not null default CURRENT_TIMESTAMP,
  image_url text null,
  features text[] null,
  components text[] null,
  block_diagram_url text null,
  working_principle text null,
  applications text[] null,
  deliverables text[] null,
  tech_specs jsonb null,
  demo_video_url text null,
  packages jsonb null,
  project_images jsonb null,
  block_diagrams jsonb null,
  project_documents jsonb null,
  constraint projects_pkey primary key (id),
  constraint projects_created_by_fkey foreign KEY (created_by) references users (id) on update CASCADE on delete set null
) TABLESPACE pg_default;
